import type { WorkspacePersonaManifest } from '../../core/types';
import { homeDefinition, managerNavigation } from '../shared';

export const companyOwnerManifest = {
  id: 'company-owner',
  status: 'authoritative',
  eligibleRoles: ['OrganizationOwner'],
  priority: 10,
  label: 'Yard-care company owner',
  description: 'Company operations, customers, teams, routes, and recovery',
  defaultView: 'home',
  navigation: managerNavigation,
  surfaces: { fieldOperations: true, customerCare: false, management: true },
  home: homeDefinition(
    'Run today with confidence.',
    'Turn great field work into a business customers trust.',
  ),
  rollout: [
    { unit: 'o1', capability: 'company_readiness' },
    { unit: 'o2', capability: 'daily_operations' },
    { unit: 'o3', capability: 'customers_and_team' },
    { unit: 'o4', capability: 'reports_and_recovery' },
  ],
  viewRequirements: {
    manager: 'company_readiness',
    route: 'daily_operations',
    jobs: 'daily_operations',
    job: 'daily_operations',
  },
  managerTools: {
    'owner-setup': 'company_readiness',
    'company-readiness': 'company_readiness',
    'day-plan': 'daily_operations',
    'dispatch-hierarchy': 'daily_operations',
    'dispatch-workload': 'daily_operations',
    'property-profile': 'customers_and_team',
    'property-service': 'customers_and_team',
    'customer-accounts': 'customers_and_team',
    'customer-portal': 'customers_and_team',
    'customer-portfolios': 'customers_and_team',
    'team-overview': 'customers_and_team',
    'team-members': 'customers_and_team',
    'team-invitations': 'customers_and_team',
    'team-activity': 'customers_and_team',
    'operations-activity': 'reports_and_recovery',
    notifications: 'reports_and_recovery',
    'completion-reports': 'reports_and_recovery',
    'visit-questions': 'reports_and_recovery',
    'photo-processing': 'reports_and_recovery',
    'operational-exceptions': 'reports_and_recovery',
    'customer-privacy': 'reports_and_recovery',
    'photo-erasure': 'reports_and_recovery',
  },
} satisfies WorkspacePersonaManifest;
